[package]
name = "guide_01"
version = "0.1.0"
authors = ["RAUI Contributors"]
edition = "2021"

publish = false

[dependencies]
# The main RAUI crate
raui = { version = "0.46", path = "../../../", features = ["app"] }
