[package]
name = "raui-material"
version = "0.38.3"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Material components library for RAUI"
readme = "../README.md"
license = "MIT"
repository = "https://github.com/RAUI-labs/raui"
keywords = ["renderer", "agnostic", "ui", "interface", "gamedev"]
categories = ["gui", "rendering::graphics-api"]

[features]
scalar64 = ["raui-core/scalar64"]
integer64 = ["raui-core/integer64"]

[dependencies]
raui-core = { path = "../raui-core", version = "0.38" }
serde = { version = "1", features = ["derive"] }
