[package]
name = "guide_03"
version = "0.1.0"
authors = ["RAUI Contributors"]
edition = "2024"

publish = false

[dependencies]
# The main RAUI crate
raui = { version = "0.66", path = "../../../", features = ["app"] }
